(defpackage #:cl-mcp/tests
  (:use #:cl)
  (:import-from #:rove)
  (:import-from #:cl-mcp/tests/bridge-test)
  #+nil(:import-from #:cl-mcp/tests/asdf-tools-test)
  (:import-from #:cl-mcp/tests/code-test)
  (:import-from #:cl-mcp/tests/core-test)
  (:import-from #:cl-mcp/tests/fs-test)
  (:import-from #:cl-mcp/tests/logging-test)
  (:import-from #:cl-mcp/tests/protocol-test)
  (:import-from #:cl-mcp/tests/repl-test)
  (:import-from #:cl-mcp/tests/cst-test)
  (:import-from #:cl-mcp/tests/lisp-read-file-test)
  (:import-from #:cl-mcp/tests/lisp-edit-form-test)
  (:import-from #:cl-mcp/tests/validate-test)
  (:import-from #:cl-mcp/tests/tcp-test)
  (:import-from #:cl-mcp/tests/tools-test)
  (:import-from #:cl-mcp/tests/define-tool-test)
  (:import-from #:cl-mcp/tests/integration-test)
  (:import-from #:cl-mcp/tests/parinfer-test)
  (:import-from #:cl-mcp/tests/http-test)
  (:import-from #:cl-mcp/tests/clgrep-utils-test)
  (:import-from #:cl-mcp/tests/clgrep-test)
  (:import-from #:cl-mcp/tests/utils-strings-test)
  (:import-from #:cl-mcp/tests/utils-hash-test)
  (:import-from #:cl-mcp/tests/utils-printing-test)
  (:import-from #:cl-mcp/tests/utils-sanitize-test)
  (:import-from #:cl-mcp/tests/utils-system-test)
  (:import-from #:cl-mcp/tests/system-loader-test)
  (:import-from #:cl-mcp/tests/paredit-test))



(in-package #:cl-mcp/tests)

(defmethod asdf:perform :after ((op asdf:test-op) (system (eql (asdf:find-system :cl-mcp/tests))))
  (let ((test-packages (remove-if-not
                        (lambda (dep)
                          (and (stringp dep)
                               (uiop:string-prefix-p "cl-mcp/tests/" dep)))
                        (asdf:system-depends-on system))))
    (rove:run test-packages)))
